Attempt to address Travis error with composer install.
Copy line from amp/travis.yml.
There were failed Travis builds:
ERROR: Referenced sniff PHPCompatibility does not exist
This may be because composer install didn't run.